### ISSUE TITLE
Request for dual-licensing

### ISSUE THREAD

**Issue by amake** [hiohiohio/omegat-plugin-externalfinder#9]
There is interest in incorporating ExternalFinder into OmegaT itself. Would you agree to license your code under GPL-3.0 as well, to make it easier to integrate? This is basically the same thing I requested for LinkBuilder in hiohiohio/omegat-plugin-linkbuilder#2.

**Comment by hiohiohio** [comment]
Hi @amake
Why not? Working on this.

**Comment by hiohiohio** [comment]
Done. Hope it helps you.

**Comment by amake** [comment]
Wonderful! Thank you very much. I will let you know when the integration is complete.

**Comment by amake** [comment]
The integration is now available in trunk, r9485 or later. It is scheduled to be released in OmegaT 4.1.0, due later this month.

**Comment by brandelune** [comment]
This issue should be closed now.
